sudo: false
language: node_js
node_js:
  - 0.10
  - 0.12
  - 4.2
before_install:
  - npm install -g npm@latest-2
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
